### ISSUE TITLE
How do I get the SSH public key

### ISSUE THREAD

**Issue by Asiya-Yunusa** [paolosalvatori/private-aks-cluster-terraform-devops#1]
https://github.com/paolosalvatori/private-aks-cluster-terraform-devops/blob/9b1aed596f0b170ee45f415a8c4b7a74caeaa544/terraform/variables.tf#L589

Hello Paolo. I will like to know how I can get the ssh public key variable for the jumphost VM. Am I meant to generate it using OpenSSL?

Thank you.

**Comment by iamvighnesh** [comment]
Yes, you are always advised to create your own set of keys and manage them in a secure that only you have access to.

OpenSSL is one of the options to create a new set of keys.

**Comment by Asiya-Yunusa** [comment]
Thank you! @iamvighnesh
